export const stories = {
    data: function () {
        return {
            titles: ['Elliot, Tinder', 'Wallie, A Robot', 'Lisa, A Buried Dream'],
            contents: [
                `
                    <p><i>Vibrate (verb): to move or make something move from side to side very quickly and with small movements.</i></p>
                    <p><i>Swig (verb): to take a quick drink of something, especially alcohol.</i></p>
                    <p><i>Shudder (verb): to shake because you are cold or frightened, or because of a strong feeling.</i></p>
                    <p><i>Scrapheap (noun): a pile of things, especially of metal, that are no longer wanted or useful.</i></p>
                    <p><i>Puberty (noun): the period of a person’s life during which their sexual organs develop and they become capable of having children.</i></p>
                    <br>
                    <p>Elliot is a fourteen-year-old teenager who has been reaching puberty as all other teenagers have to get through. As usual, “loved chemical” is awakened inside them, and Elliot has not been an exceptional instance, not avoiding it produced inside him.</p>
                    <p>One day, Elliot’s best friend had introduced him an app called Tinder which is a location-based social mobile app, used as a dating site, that allows users to chat and find their match to go on date out, and then he downloaded it and tried to build up his profile to be nice and appealling to girls. At 8.00 pm on the same day, while he was laying on the bed and shuddering at the coldness of the winter under the blanket, his phone vibrated with a Tinder notification that a female teenager actively started a conversation witha lovely greeting, “Hi! How ya going? I am Lisa”. It made him excited and wonder what he should begin and how he had to reply her message. He started typing a line with a formal response, “I am good. What are you up to then?”. That, their conversation seemed to be going well by swaping their stories, interests and hobbies each other. Enventually, they set a time and a place to meet up so that they would know more about their “temporary” partners.</p>
                    <p>One hour earlier the time they would officially catch up each other, Elliot had been thrilled and excited to go on dating with Lisa as his first girl at the first time after being alone for 14 years. He was on the bus to the meeting place, and he felt so nervous that he would be in table with only one girl and where he should begin a funny conversation. Ultimately, he had reached to their redezvous and waited for her coming, but before that he had received a message with content that she was going to be late in 15 minutes. Only 10 minutes had gone by, she appeared with… a terrible shape of obesity. As a young boy like him, he covered his face with his hands, and then tried to get out of there without getting her attention. Hurtfully, he left her alone and blocked all ways she was able to contact him through Tinder, phone number, Facebook, Instagram and Snapchat. But 10 minutes later, he had run away from there and felt guilty of his action that he completely deserved to be ready for scapheap as well as a creepy boy. Without any further hesitation, he decided to come back to their meeting and eye straight right at her. He waved his hand as sign of appealing her attention. As soon as he had reached to him, he apologized for not being on time because of traffic congestion, and then swigged water from the bottle on the table she had just ordered for waiting for him. Happily, their conversation was in the love line, and he completely wiped the bias of her shape our of his mind.</p>
                    <span>Nam Nguyen</span>
                `,
                `
                    <p><i>Accumulate (verb):  to gradually get more and more of something over a period of time.</i></p>
                    <p><i>Bewildering (adjective): making you feel confused because there are too many things to choose from or because something is difficult to understand.</i></p>
                    <p><i>Abundance (noun): a large quantity that is more than enough.</i></p>
                    <p><i>Compound (verb): to make something bad become even worse by causing further damage or problems.</i></p>
                    <p><i>Stink (verb): to have a strong, unpleasant smell.</i></p>
                    <p>Wallie is a little lovely robot. He was the only one left on Mars since everyone had migrated to a new planet called Earth. Everyday, he collected and reused the remaining trash on this planet during the daytime, and he spent his night doing abundance of researches and trying to invent a machine which refreshes the atmosphere and stimulates creatures growing up on this no-dreaming planet. He put all the effort as well as endeavor on the machine for only one reason that he strived to get human beings back to this planet. Since he never gave up and accumulated enough knowledge through research and self-taught over many years, he eventually invented the machine called “Max”, a savior and a hero of Mars. It is a system that compounds machine learning with artificial intelligence. It converts polluted air to fresh one, and it eliminates toxic cloud in the sky, which gets the sky back blue. Also, the oceans expand larger than they used to be. It is Max that stops compounding the problem of Mars that used to be called as “Red Planet”, but now it is definitely different, it is a combination of blue, brown, yellow, orange, and green. Therefore, human beings stop being bewildered which one is better, and do not hesitate if they are allowed to return because Wallie is willing to welcome everyone coming back the planet where they lived happily and had a whale of a time together. Now, they together build up and maintain Mars to be more beautiful than ever.</p>
                    <span>Nam Nguyen</span>
                `,
                `
                    <p><i>Pivotal (adjective): of great importance because other things depend on it.</i></p>
                    <p><i>Fumble (verb) to have difficulty speaking clearly or finding the right words to say.</i></p>
                    <p><i>Slip out of (phrasal verb): get out of somewhere without being paid attention. (Bonus: slip out - when something slips out, you say it without really intending to).</i></p>
                    <p><i>Scrutinize (verb): to look at or examine somebody/something carefully.</i></p>
                    <p><i>Perceive (verb): to understand or think of somebody/something in a particular way (this pattern is usually used in the passive).</i></p>
                    <p>A younger woman whose name is Lisa is working in a consulting company. She appears with a long blond hair, blue deep eyes and slim shape, plus the graceful physical attraction. Honestly, she is beautiful and considered as a version two of Liza Soberano from Philippines. However, this beauty has been buried in the ground for a long time after the first time she started being hired by a model company was considered as the last time she did as her parent do not allowed her to pursue model career. Therefore, she is currently working in the company from dawn to dusk with a measly salary, and the worse thing is that her eyes have to stick on the screen 8 hours straight. She sometimes wonders whether she is letting her time pass through her life meaninglessly and accepting the sustain life with walking-dead daily body.</p>
                    <p>One day, she would be responsible for hosting a pivotal meeting where her boss was going to deal with a big partner in a cost-highly project. She felt overwhelmed like a lot of rocks were being pressed down on her shoulder under the constant pressure. If she had not done it well, she would have got fired and her company could have lost a big opportunity working with one of huge partners on the competitive market. The day before the meeting officially day was the testing day on her work after her 10-day preparation. Her boss scrutinized carefully her organization, performance and report she had virtually spent her all night writing that she had been half-asleep then. Unfortunately, in the middle of her presentation, she fumbled helplessly for words, and she stopped finding the right words to say that she just had forgotten them in a while. Not that she got compliment from her boss obviously. On the meeting day, she tried her best and ended with a bang that was a good sign of lucky as well as the existence of the God. Her work had been done well. While her boss was dealing with the partner, she slipped out of the room without being paid someone’s attention as at that time her boss did not need her to do him any favour. Then, she headed to convenience store and bought the most expensive ice cream for herself as a gift of hosting a successful meeting, and then continued daydreaming about the model career on the cloud 9 that it had been perceived as her “intangible” dream she have never ever approach in her own way due to family… Such dream is something intangible until we completely start to pursue it.</p>
                    <span>Nam Nguyen</span>
                `
            ],
            storyPosts: [
                {
                    id: 1,
                    title: 'Elliot, Tinder',
                    content: `
                        <p>Elliot is a fourteen-year-old teenager who has been reaching puberty as all other teenagers have to get through. As usual, “loved chemical” is awakened inside them, and Elliot has not been an exceptional instance, not avoiding it produced inside him.</p>
                        <p>One day, Elliot’s best friend had introduced him an app called Tinder which is a location-based social mobile app, used as a dating site, that allows users to chat and find their match to go on date out, and then he downloaded it and tried to build up his profile to be nice and appealling to girls. At 8.00 pm on the same day, while he was laying on the bed and shuddering at the coldness of the winter under the blanket, his phone vibrated with a Tinder notification that a female teenager actively started a conversation witha lovely greeting, “Hi! How ya going? I am Lisa”. It made him excited and wonder what he should begin and how he had to reply her message. He started typing a line with a formal response, “I am good. What are you up to then?”. That, their conversation seemed to be going well by swaping their stories, interests and hobbies each other. Enventually, they set a time and a place to meet up so that they would know more about their “temporary” partners.</p>
                        <p>One hour earlier the time they would officially catch up each other, Elliot had been thrilled and excited to go on dating with Lisa as his first girl at the first time after being alone for 14 years. He was on the bus to the meeting place, and he felt so nervous that he would be in table with only one girl and where he should begin a funny conversation. Ultimately, he had reached to their redezvous and waited for her coming, but before that he had received a message with content that she was going to be late in 15 minutes. Only 10 minutes had gone by, she appeared with… a terrible shape of obesity. As a young boy like him, he covered his face with his hands, and then tried to get out of there without getting her attention. Hurtfully, he left her alone and blocked all ways she was able to contact him through Tinder, phone number, Facebook, Instagram and Snapchat. But 10 minutes later, he had run away from there and felt guilty of his action that he completely deserved to be ready for scapheap as well as a creepy boy. Without any further hesitation, he decided to come back to their meeting and eye straight right at her. He waved his hand as sign of appealing her attention. As soon as he had reached to him, he apologized for not being on time because of traffic congestion, and then swigged water from the bottle on the table she had just ordered for waiting for him. Happily, their conversation was in the love line, and he completely wiped the bias of her shape our of his mind.</p>
                    `
                },
                {
                    id: 2,
                    title: 'Wallie, A Robot',
                    content: '<p>Wallie is a little lovely robot. He was the only one left on Mars since everyone had migrated to a new planet called Earth. Everyday, he collected and reused the remaining trash on this planet during the daytime, and he spent his night doing abundance of researches and trying to invent a machine which refreshes the atmosphere and stimulates creatures growing up on this no-dreaming planet. He put all the effort as well as endeavor on the machine for only one reason that he strived to get human beings back to this planet. Since he never gave up and accumulated enough knowledge through research and self-taught over many years, he eventually invented the machine called “Max”, a savior and a hero of Mars. It is a system that compounds machine learning with artificial intelligence. It converts polluted air to fresh one, and it eliminates toxic cloud in the sky, which gets the sky back blue. Also, the oceans expand larger than they used to be. It is Max that stops compounding the problem of Mars that used to be called as “Red Planet”, but now it is definitely different, it is a combination of blue, brown, yellow, orange, and green. Therefore, human beings stop being bewildered which one is better, and do not hesitate if they are allowed to return because Wallie is willing to welcome everyone coming back the planet where they lived happily and had a whale of a time together. Now, they together build up and maintain Mars to be more beautiful than ever.</p>'
                },
                {
                    id: 3,
                    title: 'Lisa, A Buried Dream',
                    content: `
                        <p>A younger woman whose name is Lisa is working in a consulting company. She appears with a long blond hair, blue deep eyes and slim shape, plus the graceful physical attraction. Honestly, she is beautiful and considered as a version two of Liza Soberano from Philippines. However, this beauty has been buried in the ground for a long time after the first time she started being hired by a model company was considered as the last time she did as her parent do not allowed her to pursue model career. Therefore, she is currently working in the company from dawn to dusk with a measly salary, and the worse thing is that her eyes have to stick on the screen 8 hours straight. She sometimes wonders whether she is letting her time pass through her life meaninglessly and accepting the sustain life with walking-dead daily body.</p>
                        <p>One day, she would be responsible for hosting a pivotal meeting where her boss was going to deal with a big partner in a cost-highly project. She felt overwhelmed like a lot of rocks were being pressed down on her shoulder under the constant pressure. If she had not done it well, she would have got fired and her company could have lost a big opportunity working with one of huge partners on the competitive market. The day before the meeting officially day was the testing day on her work after her 10-day preparation. Her boss scrutinized carefully her organization, performance and report she had virtually spent her all night writing that she had been half-asleep then. Unfortunately, in the middle of her presentation, she fumbled helplessly for words, and she stopped finding the right words to say that she just had forgotten them in a while. Not that she got compliment from her boss obviously. On the meeting day, she tried her best and ended with a bang that was a good sign of lucky as well as the existence of the God. Her work had been done well. While her boss was dealing with the partner, she slipped out of the room without being paid someone’s attention as at that time her boss did not need her to do him any favour. Then, she headed to convenience store and bought the most expensive ice cream for herself as a gift of hosting a successful meeting, and then continued daydreaming about the model career on the cloud 9 that it had been perceived as her “intangible” dream she have never ever approach in her own way due to family… Such dream is something intangible until we completely start to pursue it.</p>
                    `
                }
            ],
        }
    }
}